//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YouLearn.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MSG {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MSG() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YouLearn.Domain.Resources.MSG", typeof(MSG).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A {0} deve ser maior ou igual a {1}..
        /// </summary>
        internal static string A_X0_DEVE_SER_MAIOR_OU_IGUAL_A_X1 {
            get {
                return ResourceManager.GetString("A_X0_DEVE_SER_MAIOR_OU_IGUAL_A_X1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados não encontrados..
        /// </summary>
        internal static string DADOS_NAO_ENCONTRADOS {
            get {
                return ResourceManager.GetString("DADOS_NAO_ENCONTRADOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este {0} já existe..
        /// </summary>
        internal static string ESTE_X0_JA_EXISTE {
            get {
                return ResourceManager.GetString("ESTE_X0_JA_EXISTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe {0} {1} com o {2} {3}..
        /// </summary>
        internal static string JA_EXISTE_XART_X0_COM_O_X1_X2 {
            get {
                return ResourceManager.GetString("JA_EXISTE_XART_X0_COM_O_X1_X2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é possível excluir {0} {1} associado a {2} {3}..
        /// </summary>
        internal static string NAO_E_POSSIVEL_EXCLUIR_XART_X1_ASSOCIADO_A_XART_X2 {
            get {
                return ResourceManager.GetString("NAO_E_POSSIVEL_EXCLUIR_XART_X1_ASSOCIADO_A_XART_X2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objeto {0} é obrigatório..
        /// </summary>
        internal static string OBJETO_X0_E_OBRIGATORIO {
            get {
                return ResourceManager.GetString("OBJETO_X0_E_OBRIGATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operação realizada com sucesso..
        /// </summary>
        internal static string OPERACAO_REALIZADA_COM_SUCESSO {
            get {
                return ResourceManager.GetString("OPERACAO_REALIZADA_COM_SUCESSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} é obrigatório..
        /// </summary>
        internal static string X0_E_OBRIGATORIO {
            get {
                return ResourceManager.GetString("X0_E_OBRIGATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} é obrigatório e deve conter entre {1} e {2} caracteres.
        /// </summary>
        internal static string X0_E_OBRIGATORIO_E_DEVE_CONTER_ENTRE_X1_E_X2_CARACTERES {
            get {
                return ResourceManager.GetString("X0_E_OBRIGATORIO_E_DEVE_CONTER_ENTRE_X1_E_X2_CARACTERES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} é obrigatório e deve conter {1} caracteres.
        /// </summary>
        internal static string X0_E_OBRIGATORIO_E_DEVE_CONTER_X1_CARACTERES {
            get {
                return ResourceManager.GetString("X0_E_OBRIGATORIO_E_DEVE_CONTER_X1_CARACTERES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} inválid{1}.
        /// </summary>
        internal static string X0_INVALID_XART {
            get {
                return ResourceManager.GetString("X0_INVALID_XART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} não informad{1}.
        /// </summary>
        internal static string X0_NAO_INFORMAD_XART {
            get {
                return ResourceManager.GetString("X0_NAO_INFORMAD_XART", resourceCulture);
            }
        }
    }
}
